negativeLogin
germange/Protractor pull request #1
Opened 2020-04-21 13:09 UTC by germange

Negative log in test added;
getErrorMessage, clearEmail methods added to the home page;

2020-04-21 13:40 UTC, nbabii requested changes
Please review and fix a few comments

2020-04-21 13:40 UTC, nbabii commented on pageObject/loginPage.js
> +let errorMessageLocator = by.css('ol > li');
Please try to improve locator, use some class name or ID. Because each html ordered list have this structure `ol > li`

2020-04-21 13:40 UTC, nbabii commented on pageObject/loginPage.js
> +        return allure.createStep(`Warning text verification`, async ()=> {
No need for allure step for reading texts

2020-04-21 13:40 UTC, nbabii commented on conf.js
> +          await createScreenshotAllure();
Please also do a restart of browser after each spec file

2020-04-22 06:20 UTC, nbabii commented
@germange now it looks fine, the final step is to get our code looks nice. Please review these rules and use them starting current PR
https://google.github.io/styleguide/jsguide.html#formatting

2020-04-23 09:04 UTC, germange commented
all errors reported by lint were removed by  last comit

2020-04-23 09:06 UTC, merged